version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile # Especifica o Dockerfile
    ports:
      - "3000:80" # Mapeie a porta 80 do contêiner para a porta 3000 do host
    volumes:
      - .:/app # Monta o diretório atual para o contêiner
    environment:
      - NODE_ENV=production
